#!/usr/bin/env node
/**
 * Node tests for the sizing JS shipped inside the Rich UI player document.
 *
 * The document is generated by the Python module (video_embedder) and written
 * to a temp file; this harness extracts the <script> and runs it against a
 * minimal DOM mock (no jsdom dependency) using node's `vm` module. The mock
 * provides only what the script touches: document/window/screen/parent/
 * ResizeObserver, players with data-ar, videos with videoWidth/videoHeight
 * and event registration.
 *
 * Run:  python3 -m video_embedder_dump /tmp/player.html  (or see Makefile)
 *       node tests/player_js.test.js /tmp/player.html
 */

const fs = require('fs');
const vm = require('vm');

const HTML_PATH = process.argv[2];
if (!HTML_PATH) {
  console.error('usage: node tests/player_js.test.js <player.html>');
  process.exit(1);
}

let passed = 0;
let failed = 0;
function test(name, fn) {
  try {
    fn();
    passed++;
    console.log(`  ok  ${name}`);
  } catch (e) {
    failed++;
    console.error(`FAIL  ${name}\n      ${e.message}`);
  }
}
function eq(actual, expected, msg) {
  if (actual !== expected) {
    throw new Error(`${msg || 'eq'}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
  }
}
function close(actual, expected, tol, msg) {
  if (Math.abs(actual - expected) > tol) {
    throw new Error(`${msg || 'close'}: expected ~${expected}, got ${actual}`);
  }
}

// ---------------------------------------------------------------------------
// Minimal DOM mock
// ---------------------------------------------------------------------------
function makePlayer({ tag = 'iframe', ar = null, video = null, clientWidth = null } = {}) {
  const listeners = {};
  const p = {
    dataset: {},
    style: {},
    tag,
    _listeners: listeners,
    querySelector(sel) {
      if (sel === 'video' && tag === 'video') return video;
      return null;
    },
  };
  if (ar) p.dataset.ar = ar;
  if (tag === 'video' && video) {
    video._player = p;
  }
  return p;
}

function makeVideo({ videoWidth = 0, videoHeight = 0 } = {}) {
  const listeners = {};
  return {
    videoWidth,
    videoHeight,
    addEventListener(type, fn) { (listeners[type] = listeners[type] || []).push(fn); },
    _listeners: listeners,
    _fire(type) { (listeners[type] || []).forEach((fn) => fn()); },
  };
}

function makeContext({ players = [], clientWidth = 800, availHeight = 800, screenHeight = 800, scrollHeight = 400, stackHeight = null } = {}) {
  const messages = [];
  const windowListeners = {};
  const globalListeners = {};
  const videos = players
    .filter((p) => p.tag === 'video')
    .map((p) => p.querySelector('video'));
  const stack = { offsetHeight: stackHeight === null ? null : stackHeight };

  const document = {
    documentElement: {
      clientWidth,
      scrollHeight,
    },
    body: { _observed: 0 },
    getElementById(id) {
      if (id === 'stack') return stack;
      return null;
    },
    querySelectorAll(sel) {
      if (sel === '.player') return players;
      if (sel === 'video') return videos;
      return [];
    },
  };

  const context = {
    document,
    window: {
      addEventListener(type, fn) { (windowListeners[type] = windowListeners[type] || []).push(fn); },
    },
    screen: { availHeight, height: screenHeight },
    parent: {
      postMessage(msg, target) { messages.push({ msg, target }); },
    },
    addEventListener(type, fn) { (globalListeners[type] = globalListeners[type] || []).push(fn); },
    ResizeObserver: class {
      constructor(fn) { this._fn = fn; }
      observe(el) { el._observed = (el._observed || 0) + 1; }
      fire() { this._fn(); }
    },
    // helpers exposed to the test
    __messages: messages,
    __windowListeners: windowListeners,
    __globalListeners: globalListeners,
    __videos: videos,
    __body: document.body,
    __stack: stack,
  };

  return context;
}

// ---------------------------------------------------------------------------
// Extract and run the player script
// ---------------------------------------------------------------------------
function runPlayerScript(html, ctx) {
  const m = html.match(/<script>([\s\S]*?)<\/script>/);
  if (!m) throw new Error('no <script> found in player document');
  vm.createContext(ctx);
  vm.runInContext(m[1], ctx, { filename: 'player.js' });
}

const html = fs.readFileSync(HTML_PATH, 'utf8');
console.log(`Testing player script from ${HTML_PATH}\n`);

// --- 1. video: uses real dimensions once loaded (16:9) ---------------------
test('video sizes from loadedmetadata ratio (1920x1080 -> 16/9)', () => {
  const video = makeVideo({ videoWidth: 1920, videoHeight: 1080 });
  const player = makePlayer({ tag: 'video', video, clientWidth: 800 });
  const ctx = makeContext({ players: [player], clientWidth: 800, availHeight: 800 });
  runPlayerScript(html, ctx);
  // fit() runs at the end of the script: width = min(800, maxH*r)
  const maxH = 800 * 0.65; // 520
  const wByH = maxH * (1920 / 1080); // 924.4 > 800
  eq(player.style.width, '800px', 'width fills container when cap not binding');
  close(parseFloat(player.style.height), 800 / (1920 / 1080), 0.01, 'height from ratio');
});

test('height cap binds on wide container (65% of screen.availHeight)', () => {
  const video = makeVideo({ videoWidth: 1920, videoHeight: 1080 });
  const player = makePlayer({ tag: 'video', video });
  const ctx = makeContext({ players: [player], clientWidth: 2000, availHeight: 800 });
  runPlayerScript(html, ctx);
  const maxH = 520;
  const w = maxH * (16 / 9);
  close(parseFloat(player.style.height), maxH, 0.01, 'height capped at 65%');
  close(parseFloat(player.style.width), w, 0.5, 'width derived from capped height');
  eq(parseFloat(player.style.height) <= maxH, true, 'height never exceeds cap');
});

// --- 2. iframe: uses data-ar from yt-dlp metadata --------------------------
test('iframe uses data-ar (9/16 portrait)', () => {
  const player = makePlayer({ tag: 'iframe', ar: '9/16' });
  const ctx = makeContext({ players: [player], clientWidth: 800, availHeight: 800 });
  runPlayerScript(html, ctx);
  const maxH = 520;
  const wByH = maxH * (9 / 16); // 292.5 < 800
  close(parseFloat(player.style.width), wByH, 0.5, 'width from portrait ratio');
  close(parseFloat(player.style.height), 292.5 / (9 / 16), 0.01, 'height from ratio');
});

test('iframe falls back to 16/9 without data-ar', () => {
  const player = makePlayer({ tag: 'iframe' });
  const ctx = makeContext({ players: [player], clientWidth: 400, availHeight: 800 });
  runPlayerScript(html, ctx);
  eq(player.style.width, '400px', 'fills width');
  close(parseFloat(player.style.height), 400 / (16 / 9), 0.01, '16/9 height');
});

test('degenerate data-ar falls back to 16/9', () => {
  const player = makePlayer({ tag: 'iframe', ar: '0/0' });
  const ctx = makeContext({ players: [player], clientWidth: 400, availHeight: 800 });
  runPlayerScript(html, ctx);
  close(parseFloat(player.style.height), 400 / (16 / 9), 0.01, '16/9 height for 0/0');
});

// --- 3. screen degradation -------------------------------------------------
test('zero availHeight (webview) -> no cap, full width', () => {
  const video = makeVideo({ videoWidth: 1920, videoHeight: 1080 });
  const player = makePlayer({ tag: 'video', video });
  const ctx = makeContext({ players: [player], clientWidth: 1200, availHeight: 0, screenHeight: 0 });
  runPlayerScript(html, ctx);
  eq(player.style.width, '1200px', 'full width when screen unknown');
  close(parseFloat(player.style.height), 1200 / (16 / 9), 0.01, 'height from ratio');
});

// --- 4. multiple players, each sized by its own ratio ----------------------
test('multiple players sized independently', () => {
  const v16 = makeVideo({ videoWidth: 1920, videoHeight: 1080 });
  const p16 = makePlayer({ tag: 'video', video: v16 });
  const p9 = makePlayer({ tag: 'iframe', ar: '9/16' });
  const ctx = makeContext({ players: [p16, p9], clientWidth: 800, availHeight: 800 });
  runPlayerScript(html, ctx);
  const maxH = 520;
  eq(p16.style.width, '800px', 'landscape fills width');
  const w9 = maxH * (9 / 16);
  close(parseFloat(p9.style.width), w9, 0.5, 'portrait capped by height');
  close(parseFloat(p9.style.height), maxH, 0.5, 'portrait height == cap');
});

// --- 5. reportHeight -------------------------------------------------------
test('reportHeight posts iframe:height with the stack height (not scrollHeight)', () => {
  const player = makePlayer({ tag: 'iframe', ar: '16/9' });
  const ctx = makeContext({ players: [player], clientWidth: 800, availHeight: 800, stackHeight: 482 });
  runPlayerScript(html, ctx);
  const last = ctx.__messages[ctx.__messages.length - 1];
  eq(last.target, '*', 'postMessage target *');
  eq(last.msg.type, 'iframe:height', 'message type');
  eq(last.msg.height, 482, 'height = stack.offsetHeight (content height, hugs the player)');
});

test('reportHeight falls back to scrollHeight when stack has no height', () => {
  const player = makePlayer({ tag: 'iframe', ar: '16/9' });
  const ctx = makeContext({ players: [player], clientWidth: 800, availHeight: 800, stackHeight: 0, scrollHeight: 412 });
  runPlayerScript(html, ctx);
  const last = ctx.__messages[ctx.__messages.length - 1];
  eq(last.msg.height, 412, 'fallback to documentElement.scrollHeight');
});

// --- 6. event wiring -------------------------------------------------------
test('registers loadedmetadata/loadeddata/canplay + load/resize + observer', () => {
  const video = makeVideo({ videoWidth: 0, videoHeight: 0 });
  const player = makePlayer({ tag: 'video', video });
  const ctx = makeContext({ players: [player] });
  runPlayerScript(html, ctx);
  ['loadedmetadata', 'loadeddata', 'canplay'].forEach((t) => {
    eq(video._listeners[t] && video._listeners[t].length >= 1, true, `video listens ${t}`);
  });
  eq(ctx.__windowListeners.load && ctx.__windowListeners.load.length >= 1, true, 'window load');
  eq(ctx.__globalListeners.resize && ctx.__globalListeners.resize.length >= 1, true, 'global resize');
  eq(ctx.__body._observed, 1, 'ResizeObserver observes body');
});

// --- 7. re-fit when metadata arrives late ----------------------------------
test('re-fits on loadedmetadata after initial zero-size fit', () => {
  const video = makeVideo({ videoWidth: 0, videoHeight: 0 });
  const player = makePlayer({ tag: 'video', video });
  const ctx = makeContext({ players: [player], clientWidth: 800, availHeight: 800 });
  runPlayerScript(html, ctx);
  // initial fit with no metadata: uses data-ar fallback (none -> 16/9)
  eq(player.style.width, '800px', 'initial width');
  // metadata arrives -> fire loadedmetadata -> real ratio
  video.videoWidth = 1080;
  video.videoHeight = 1920;
  video._fire('loadedmetadata');
  const maxH = 520;
  const wByH = maxH * (1080 / 1920); // 292.5
  close(parseFloat(player.style.width), wByH, 0.5, 're-fit to portrait ratio');
  close(parseFloat(player.style.height), maxH, 0.5, 're-fit height capped');
});

// --- 8. resize observer refits ---------------------------------------------
test('ResizeObserver refit reflects new container width', () => {
  const player = makePlayer({ tag: 'iframe', ar: '16/9' });
  const ctx = makeContext({ players: [player], clientWidth: 400, availHeight: 800 });
  runPlayerScript(html, ctx);
  eq(player.style.width, '400px', 'initial');
  const obs = ctx.__body._observed ? new ctx.ResizeObserver(() => {}) : null; // construct fresh
  // simulate resize by changing clientWidth and firing stored observer fn
  // (we re-run fit through the registered observer via the stored fn)
  const storedFn = ctx.__globalListeners.resize[0];
  ctx.document.documentElement.clientWidth = 700;
  storedFn();
  eq(player.style.width, '700px', 'refit to 700');
});

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
